//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passwordify.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Passwordify.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your parameters.
        /// </summary>
        public static string ChooseParametersText {
            get {
                return ResourceManager.GetString("ChooseParametersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyToClipboardText {
            get {
                return ResourceManager.GetString("CopyToClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string GenerateText {
            get {
                return ResourceManager.GetString("GenerateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Numbers.
        /// </summary>
        public static string IncludeNumberText {
            get {
                return ResourceManager.GetString("IncludeNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Special Chars.
        /// </summary>
        public static string IncludeSpecialCharsText {
            get {
                return ResourceManager.GetString("IncludeSpecialCharsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Uppercase.
        /// </summary>
        public static string IncludeUppercaseText {
            get {
                return ResourceManager.GetString("IncludeUppercaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying password. Please, try again or copy the value manually.
        /// </summary>
        public static string PasswordCopyErrorMessage {
            get {
                return ResourceManager.GetString("PasswordCopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Length ({0}).
        /// </summary>
        public static string PasswordLengthTextFormat {
            get {
                return ResourceManager.GetString("PasswordLengthTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password copied!.
        /// </summary>
        public static string PasswordSuccesfullyCopiedMessage {
            get {
                return ResourceManager.GetString("PasswordSuccesfullyCopiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ResultText {
            get {
                return ResourceManager.GetString("ResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your password on the fly.
        /// </summary>
        public static string TitleHeading {
            get {
                return ResourceManager.GetString("TitleHeading", resourceCulture);
            }
        }
    }
}
